nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  christopherpaul:
    npmAlwaysAuth: false
    npmAuthIdent: ""
    npmAuthToken: ""
    npmPublishRegistry: "http://localhost:4873"
    npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.2.0.cjs
