yarnPath: .yarn/releases/yarn-3.2.0.cjs
npmRegistryServer: "https://registry.yarnpkg.com"
npmScopes:
  christopherpaul:
    npmPublishRegistry: "http://localhost:4873"
    npmRegistryServer: "http://localhost:4873"
    npmAlwaysAuth: "false"
    npmAuthIdent: ""
    npmAuthToken: ""
unsafeHttpWhitelist:
  - "localhost"
